/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2 SP1
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Bootloadable.h"
#include "Pin_AntennaAuxOut.h"
#include "Pin_AntennaAuxOut_aliases.h"
#include "Pin_Opamp2P.h"
#include "Pin_Opamp2P_aliases.h"
#include "Pin_Opamp2Out.h"
#include "Pin_Opamp2Out_aliases.h"
#include "ADC.h"
#include "Pin_BandSel.h"
#include "Pin_BandSel_aliases.h"
#include "Pin_Opamp2M.h"
#include "Pin_Opamp2M_aliases.h"
#include "Pin_Gain2.h"
#include "Pin_Gain2_aliases.h"
#include "Opamp_2.h"
#include "Clock_12M.h"
#include "Pin_PWM_VRef.h"
#include "Pin_PWM_VRef_aliases.h"
#include "Clock_MIX.h"
#include "Clock_ADC.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "Pin_Gain1.h"
#include "Pin_Gain1_aliases.h"
#include "Pin_BandSel2.h"
#include "Pin_BandSel2_aliases.h"
#include "AMux_CapSw.h"
#include "Pin_LED.h"
#include "Pin_LED_aliases.h"
#include "Pin_CMOD.h"
#include "Pin_CMOD_aliases.h"
#include "Pin_CTANK.h"
#include "Pin_CTANK_aliases.h"
#include "Pin_SW.h"
#include "Pin_SW_aliases.h"
#include "Opamp_1.h"
#include "Pin_Opamp1M.h"
#include "Pin_Opamp1M_aliases.h"
#include "Pin_Opamp1P.h"
#include "Pin_Opamp1P_aliases.h"
#include "Pin_Opamp1Out.h"
#include "Pin_Opamp1Out_aliases.h"
#include "Clock_AntennaAux.h"
#include "PWM_Tune.h"
#include "Pin_TunePWMOut.h"
#include "Pin_TunePWMOut_aliases.h"
#include "Pin_ADCin_Temp.h"
#include "Pin_ADCin_Temp_aliases.h"
#include "Pin_ADCin_Lux.h"
#include "Pin_ADCin_Lux_aliases.h"
#include "Clock_PWMTune.h"
#include "Mux_Conrtol_Reg.h"
#include "Pin_Gain0.h"
#include "Pin_Gain0_aliases.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

